owner: beloralabs-connect
repo: connect-status
user-agent: beloralabs-connect
skipDeleteIssues: true

sites:
  - name: Site web
    slug: site-web
    url: https://www.belora-connect.com
  - name: Administration
    slug: admin
    url: https://admin.belora-connect.com
  - name: API
    slug: api
    url: https://api.belora-connect.com/health
  - name: API (services internes)
    slug: api-ready
    url: https://api.belora-connect.com/ready
  - name: Cartesia
    slug: cartesia
    url: https://api.cartesia.ai/
    maxResponseTime: 3000

status-website:
   cname: status.belora-connect.com
   name: Connect Status
   introTitle: "**Connect** service status"
